Fix failed build on CI
The logs on CI are as follow:

```console
error: failed to run custom build command for `cssparser v0.25.9`
##[error]failed to run custom build command for `cssparser v0.25.9`
Caused by:
  process didn't exit successfully: `/home/runner/work/miteras-cli/miteras-cli/target/debug/build/cssparser-9797c592ed86ee11/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stdout
cargo:rustc-cfg=rustc_has_pr45225
cargo:rustc-cfg=has_std__mem__MaybeUninit
cargo:rerun-if-changed=/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cssparser-0.25.9/src/tokenizer.rs

--- stderr
fatal runtime error: failed to initiate panic, error 5

warning: build failed, waiting for other jobs to finish...
##[warning]error: build failed
##[error]The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```